### ISSUE TITLE
How to use a DbContext service in the Worker Template

### ISSUE THREAD

**Issue by joaofbbg** [ardalis/CleanArchitecture.WorkerService#1]
I want to know how to use a dbcontext in this clean architecture worker service, because dbcontext is a scoped service and this will be a singleton.
I know that I need to use the Services.CreateScope thing, but the challenge is which project should it go? In the worker project? Core? or Infrastructure? and how?

For an ongoing project I'm creating a scope in Worker project, but I need to pass the scope service as a parameter, and that doesn't seem me right.

**Comment by sokopa** [comment]
I believe that the proper way should be to setup your DbContext in the Infrastructure project, maybe hidden behind an interface defined in Core.
So you would wire it up as a dependency in the Worker Project just like all EntryPointService and the InMemoryQueues. 

The problem is the EntryPointService is defined as Singleton, so it cannot depend on a scoped object. I don't see a reason why you cannot have the EntryPointService as Scoped though.

**Comment by ardalis** [comment]
Yeah, good points. I think I agree.

**Comment by joaofbbg** [comment]
@sokopa, you are right. Setting EntryPointService as a Scoped Service resolve the problem. 
I can now inject an interface in EntryPointService and inject the DbContext on his implementation on Infrastructure project, it works fine.
Thank you

**Comment by ardalis** [comment]
The latest build includes EF Core working - check it out and open a new issue if you have any questions or concerns.

**Comment by joaofbbg** [comment]
I just saw your twitch video. 
Thank you for demonstrating that integration.
